CLASSES = [
    "Speed limit (20km/h)",
    "Speed limit (30km/h)",
    "Speed limit (50km/h)",
    "Speed limit (60km/h)",
    "Speed limit (70km/h)",
    "End of speed limit",
    "Speed limit (100km/h)",
    "Speed limit (120km/h)",
    "No passing",
    "No passing for trucks",
    "Intersection with minor road",
    "Priority road",
    "Yield",
    "Stop",
    "No vehicles",
    "No trucks",
    "No entry",
    "Coution",
    "Dangerous curve to the left",
    "Dangerous curve to the right",
    "Double curve",
    "Bumpy road",
    "Slippery road",
    "Road narrows",
    "Road work",
    "Traffic signals",
    "Pedestrians",
    "Children",
    "Bicycles",
    "Beware of ice",
    "Wild animals",
    "End of speed limit",
    "Turn right",
    "Turn left",
    "Drive ahead",
    "Drive streight or right",
    "Drive streight or left",
    "Keep right",
    "Keep left",
    "Roundabout",
    "End of no passing",
    "End of no passing by trucks"
]
